dependencies:
  override:
    - yarn
  cache_directories:
      - ~/.cache/yarn

version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - run:
          name: Globally install elm
          command: yarn global add elm create-elm-app
      - run:
          name: Install elm dependencies
          command: ~/.yarn/bin/elm package install --yes
      - run:
          name: Build elm app
          command: ~/.yarn/bin/elm-app build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
